version: "3"
services:
  back-end:
    container_name: back-end
    build: back-end
    volumes:
      - assets:/workdir/back-end/assets
      - output:/workdir/front-end/output-videos
    ports:
      - "127.0.0.1:5000:5000"
  redis:
    image: "redis:alpine"
  front-end:
    container_name: front-end
    build: front-end
    volumes: 
      - assets:/workdir/back-end/assets
      - output:/workdir/front-end/output-videos
    ports:
      - "3000:3000"
volumes:
  assets:
  output:
