version: "3.9"
services:
  back-end:
    container_name: back-end
    build: back-end
    volumes:
      - assets:/code/front-end/src/assets/
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"
  front-end:
    container_name: front-end
    build: front-end
    volumes: 
      - assets:/code/front-end/src/assets/
    ports:
      - "3000:3000"
      
volumes:
  assets:
