version: "3.9"
services:
  back-end:
    container_name: back-end
    build: back-end
    volumes:
      - assets:/frontend/output-videos
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"

volumes:
  assets:
