version: "3"
services:
  back-end:
    container_name: back-end
    build: back-end
    volumes:
      - assets:/back-end/assets
    ports:
      - "4000:4000"
  redis:
    image: "redis:alpine"
  front-end:
    container_name: front-end
    build: front-end
    volumes: 
      - assets:/front-end/output-videos
      - ./back-end/assets:/back-end/assets
    ports:
      - "3000:3000"
volumes:
  assets:
